package com.natelaclaire.solitaire.ui;

public final class SolitaireGameOptions {
    private SolitaireGameOptions() {}

    public static final String[] BACK_CHOICES = {
        "black_back_dark_inner.png",
        "black_back_intricate.png",
        "black_back_light_inner.png",
        "black_back_line.png",
        "black_back_line_light.png",
        "black_back_plain.png",
        "black_back_suits.png",
        "black_back_suits_dark.png",
        "blue_back_dark_inner.png",
        "blue_back_intricate.png",
        "blue_back_light_inner.png",
        "blue_back_line.png",
        "blue_back_line_light.png",
        "blue_back_plain.png",
        "blue_back_suits.png",
        "blue_back_suits_dark.png",
        "green_back_dark_inner.png",
        "green_back_intricate.png",
        "green_back_light_inner.png",
        "green_back_line.png",
        "green_back_line_light.png",
        "green_back_plain.png",
        "green_back_suits.png",
        "green_back_suits_dark.png",
        "orange_back_dark_inner.png",
        "orange_back_intricate.png",
        "orange_back_light_inner.png",
        "orange_back_line.png",
        "orange_back_line_light.png",
        "orange_back_plain.png",
        "orange_back_suits.png",
        "orange_back_suits_dark.png",
        "purple_back_dark_inner.png",
        "purple_back_intricate.png",
        "purple_back_light_inner.png",
        "purple_back_line.png",
        "purple_back_line_light.png",
        "purple_back_plain.png",
        "purple_back_suits.png",
        "purple_back_suits_dark.png",
        "red_back_dark_inner.png",
        "red_back_intricate.png",
        "red_back_light_inner.png",
        "red_back_line.png",
        "red_back_line_light.png",
        "red_back_plain.png",
        "red_back_suits.png",
        "red_back_suits_dark.png"
    };
}
